name: Ejecutar segun la rama

on:
  push:
    branches: [main, develop, feature/*]
  workflow_dispatch:

jobs:
    checkout:
      runs-on: ubuntu-latest
      steps:
      - name: Revisar codigo
        uses: actions/checkout@v4

    rama:
      runs-on: ubuntu-latest
      steps:
      - name: notificar discord (solo main)
        if: github.ref == 'refs/heads/main'
        run: |
          curl -H "Content-Type: application/json" -X POST -d '{"content":"🚀 El código se ha actualizado en la rama main."}' ${{ secrets.DISCORD_WEBHOOK_URL }}
          
      - name: notificar email
        if: github.ref == 'refs/heads/develop' || startsWith(github.ref, 'refs/heads/feature/')
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com  # Or your SMTP server
          server_port: 465
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: GitHub Action Notification
          body: 'A push was made to the main branch.'
          to: recipient@example.com
          from: sender@example.com