name: Ejecutar segun la rama

on:
  push:
    branches: [main, develop, feature/*]
  workflow_dispatch:

jobs:
    checkout:
      runs-on: ubuntu-latest
      steps:
      - name: Revisar codigo
        uses: actions/checkout@v4

    rama:
      runs-on: ubuntu-latest
      steps:
      - name: Revisar codigo
        uses: actions/checkout@v4
        
      - name: notificar discord (solo main)
        if: github.ref == 'refs/heads/main'
        run: |
          curl -H "Content-Type: application/json" -X POST -d '{"content":"🚀 El código se ha actualizado en la rama main."}' ${{ secrets.DISCORD_WEBHOOK_URL }}

      - name: Enviar correo (en develop y feature/*) 📧
        if: github.ref == 'refs/heads/develop' || startsWith(github.ref, 'refs/heads/feature/')
        run: |
          curl -X POST -H 'Content-type: application/json' --data '{"text":"${{ github.event.head_commit.message }}", "commit":"${{ github.event.head_commit.message }}", "autor":"${{ github.event.head_commit.author.name }}"}' ${{ secrets.SLACK_WEBHOOK_URL }}